// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPlaylistFromFile(arg1, arg2) {
  return window['go']['main']['App']['AddPlaylistFromFile'](arg1, arg2);
}

export function AddPlaylistFromURL(arg1, arg2) {
  return window['go']['main']['App']['AddPlaylistFromURL'](arg1, arg2);
}

export function DeletePlaylist(arg1) {
  return window['go']['main']['App']['DeletePlaylist'](arg1);
}

export function GetChannels(arg1) {
  return window['go']['main']['App']['GetChannels'](arg1);
}

export function GetPlaylists() {
  return window['go']['main']['App']['GetPlaylists']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function UpdatePlaylistChannels(arg1) {
  return window['go']['main']['App']['UpdatePlaylistChannels'](arg1);
}
