// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddPlaylistFromFile(arg1:Array<number>,arg2:string):Promise<number>;

export function AddPlaylistFromURL(arg1:string,arg2:string):Promise<number>;

export function DeletePlaylist(arg1:number):Promise<void>;

export function GetChannels(arg1:number):Promise<Array<main.Channel>>;

export function GetPlaylists():Promise<Array<main.Playlist>>;

export function Greet(arg1:string):Promise<string>;

export function UpdatePlaylistChannels(arg1:number):Promise<void>;
